server:
  port: 8081

spring:
  application:
    name: DinkyLinkApi
  datasource:
    url: jdbc:postgresql://localhost:5432/dinkylink
    username: dinkylink
    password: dinkylink
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
